services:
  kafka:
    image: apache/kafka:latest
    environment:
     KAFKA_ENABLE_KRAFT: yes
     KAFKA_PROCESS_ROLES: broker,controller
     KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
     KAFKA_BROKER_ID: 1
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     KAFKA_NUM_PARTITIONS: 3
    ports:
    - 9092:9092
    networks:
      - mysql-network
  notifications:
    image: vvravikiran/notifications:2.0
    ports:
      - 8090:8090
    networks:
      - mysql-network
  mypostgres:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=walnut16@
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    command: |
      postgres 
      -c wal_level=logical
    networks:
      - mysql-network
  trip:
    image: vvravikiran/trip
    ports:
     - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=walnut16@
    networks:
      - mysql-network
networks:
  mysql-network:
    name: mysql-network